import 'package:flutter/material.dart';
import 'package:matrimonial_app/models/profile.dart';

//dummy data generated by claude ai

List<Profile> dummyFemaleProfiles = [

  // ── Lahore ──────────────────────────────────────────────────────────────────

  Profile(
    id: 'f1',
    name: 'Aisha Malik',
    age: 22,
    city: 'Lahore',
    hobbies: [Hobby.reading, Hobby.calligraphy, Hobby.cooking],
    traits: [Trait.religious, Trait.kind, Trait.patient],
    description:
    'Assalamu Alaikum. I am a simple girl from Lahore who values deen above all else. '
        'I enjoy reading Islamic literature and practising calligraphy in my free time. '
        'I am looking for a partner who is God-fearing, responsible, and values family. '
        'My wali is my father and all communication should go through him.',
    imageUrl: 'assets/roses.jpg',
    contact: '+92-300-1234567',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f2',
    name: 'Fatima Chaudhry',
    age: 25,
    city: 'Lahore',
    hobbies: [Hobby.cooking, Hobby.gardening, Hobby.writing],
    traits: [Trait.hardworking, Trait.caring, Trait.ambitious],
    description:
    'Salam! I am a working professional in Lahore with a passion for cooking '
        'and growing my own herbs. I believe a home is built on mutual respect and '
        'honest communication. I am looking for someone mature, settled, and ready '
        'to start a family. Please have your family contact my wali directly.',
    imageUrl: 'assets/sunflowers.jpg',
    contact: '+92-321-9876543',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f3',
    name: 'Zainab Iqbal',
    age: 19,
    city: 'Lahore',
    hobbies: [Hobby.painting, Hobby.reading, Hobby.photography],
    traits: [Trait.creative, Trait.introverted, Trait.kind],
    description:
    'Hi, I am Zainab. I am still in university but my family has decided to begin '
        'the rishta process early. I am artistically inclined — I paint and do photography '
        'as a hobby. I am looking for someone patient and understanding who will give me '
        'time to grow alongside them. All communication through my father please.',
    imageUrl: 'assets/bluebells.jpg',
    contact: '+92-300-5554433',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f21',
    name: 'Ayesha Khan',
    age: 22,
    city: 'Lahore',
    hobbies: [Hobby.reading, Hobby.cooking, Hobby.gardening],
    traits: [Trait.religious, Trait.familyOriented, Trait.kind],
    description:
    'Assalamu Alaikum. I am a practicing Muslimah from Lahore seeking a pious partner. '
        'I am currently pursuing a degree in Islamic Studies. '
        'I believe a home built on deen is a home built to last.',
    imageUrl: 'assets/daisies.webp',
    contact: '+92-300-1234568',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f28',
    name: 'Zainab Hassan',
    age: 24,
    city: 'Lahore',
    hobbies: [Hobby.photography, Hobby.travelling],
    traits: [Trait.modern, Trait.ambitious, Trait.kind],
    description:
    'Salam! I am a digital marketer from Lahore with a creative side. '
        'I am looking for a progressive partner who supports personal growth '
        'and shares a sense of adventure.',
    imageUrl: 'assets/lillies.jpg',
    contact: '+92-333-9012346',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  // ── Islamabad ───────────────────────────────────────────────────────────────

  Profile(
    id: 'f4',
    name: 'Maryam Siddiqui',
    age: 27,
    city: 'Islamabad',
    hobbies: [Hobby.fitness, Hobby.travelling, Hobby.reading],
    traits: [Trait.ambitious, Trait.extroverted, Trait.hardworking],
    description:
    'Assalamu Alaikum. I am a doctor based in Islamabad. I take my deen seriously '
        'and try to balance my professional life with my responsibilities as a Muslim woman. '
        'I am looking for someone equally driven, who understands the demands of a medical '
        'career and supports personal growth. Serious proposals only via my wali.',
    imageUrl: 'assets/orchids.webp',
    contact: '+92-333-1122334',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f5',
    name: 'Hira Baig',
    age: 24,
    city: 'Islamabad',
    hobbies: [Hobby.writing, Hobby.photography, Hobby.travelling],
    traits: [Trait.creative, Trait.funny, Trait.extroverted],
    description:
    'Salam! I am a journalist in Islamabad with a love for storytelling '
        'and exploring new places. I am fun to be around but I take marriage very seriously. '
        'Looking for someone who can be both my best friend and my partner in deen. '
        'My brother is my wali and can be reached below.',
    imageUrl: 'assets/violets.jpg',
    contact: '+92-311-6677889',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f6',
    name: 'Noor Fatima',
    age: 21,
    city: 'Islamabad',
    hobbies: [Hobby.cooking, Hobby.calligraphy, Hobby.gardening],
    traits: [Trait.religious, Trait.patient, Trait.caring],
    description:
    'Assalamu Alaikum. I am a quiet and home-loving person from Islamabad. '
        'I enjoy cooking for family and practising Islamic calligraphy. My goal in life '
        'is to be a good wife and mother. I am looking for a practicing Muslim who '
        'values simplicity and sincerity. Proposals through my father only.',
    imageUrl: 'assets/tulips.jpg',
    contact: '+92-300-9988776',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f23',
    name: 'Zahra Malik',
    age: 19,
    city: 'Islamabad',
    hobbies: [Hobby.reading, Hobby.writing, Hobby.photography],
    traits: [Trait.religious, Trait.humble, Trait.patient],
    description:
    'Assalamu Alaikum. I am studying literature at university in Islamabad. '
        'I come from a respected family with strong Islamic values. '
        'I am looking for someone sincere and God-fearing to build a life with.',
    imageUrl: 'assets/bluebells.jpg',
    contact: '+92-333-3456780',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f30',
    name: 'Saima Qureshi',
    age: 28,
    city: 'Islamabad',
    hobbies: [Hobby.painting, Hobby.crafts],
    traits: [Trait.educated, Trait.kind, Trait.honest],
    description:
    'Salam! I am an architect in Islamabad and an artist at heart. '
        'I am looking for an understanding and supportive life partner who '
        'appreciates both creativity and commitment.',
    imageUrl: 'assets/sunflowers.jpg',
    contact: '+92-321-1234568',
    status: FemaleMaritalStatus.divorcee,
    hasChildren: false,
    isShortListed: false,
  ),

  // ── Karachi ─────────────────────────────────────────────────────────────────

  Profile(
    id: 'f7',
    name: 'Sara Ahmed',
    age: 26,
    city: 'Karachi',
    hobbies: [Hobby.fitness, Hobby.cooking, Hobby.reading],
    traits: [Trait.hardworking, Trait.caring, Trait.ambitious],
    description:
    'Hello! I am Sara, a software engineer living in Karachi. I love what I do '
        'but I also know that a career is not everything. I want to build a home '
        'filled with laughter, respect and Islamic values. Looking for a mature and '
        'settled partner. Please contact my uncle who is my wali.',
    imageUrl: 'assets/poppies.jpg',
    contact: '+92-321-4455667',
    status: FemaleMaritalStatus.widowed,
    hasChildren: true,
    isShortListed: false,
  ),

  Profile(
    id: 'f8',
    name: 'Khadija Rizvi',
    age: 23,
    city: 'Karachi',
    hobbies: [Hobby.painting, Hobby.calligraphy, Hobby.writing],
    traits: [Trait.creative, Trait.introverted, Trait.religious],
    description:
    'Salam. I am Khadija, an architecture student in Karachi with a deep love '
        'for Islamic art and design. I am quiet by nature but expressive through '
        'my work. I am looking for someone who appreciates art, values knowledge, '
        'and has a strong connection with Allah. Wali contact below.',
    imageUrl: 'assets/bluebells.jpg',
    contact: '+92-333-7788990',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f9',
    name: 'Ruqayyah Naqvi',
    age: 29,
    city: 'Karachi',
    hobbies: [Hobby.travelling, Hobby.reading, Hobby.fitness],
    traits: [Trait.patient, Trait.extroverted, Trait.funny],
    description:
    'Assalamu Alaikum. At 29 I know exactly what I want — a partner who is '
        'kind, God-fearing and ready to build something real. I am a physiotherapist '
        'who loves to travel and stay active. I have a good sense of humour and '
        'I believe a marriage should have joy in it. Contact my father for proposals.',
    imageUrl: 'assets/Daffodils.webp',
    contact: '+92-300-1122003',
    status: FemaleMaritalStatus.widowed,
    hasChildren: true,
    isShortListed: false,
  ),

  Profile(
    id: 'f22',
    name: 'Fatima Shah',
    age: 25,
    city: 'Karachi',
    hobbies: [Hobby.painting, Hobby.travelling],
    traits: [Trait.educated, Trait.modern, Trait.ambitious],
    description:
    'Salam! I am an MBA graduate working in finance in Karachi. '
        'I am looking for a supportive partner who values both education and family. '
        'I want someone who understands that ambition and good character can coexist.',
    imageUrl: 'assets/poppies.jpg',
    contact: '+92-321-2345679',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f29',
    name: 'Aisha Mahmood',
    age: 21,
    city: 'Karachi',
    hobbies: [Hobby.cooking, Hobby.reading, Hobby.gardening],
    traits: [Trait.familyOriented, Trait.religious, Trait.humble],
    description:
    'Assalamu Alaikum. I am studying Islamic sciences in Karachi while '
        'helping manage family responsibilities. I am seeking a partner who '
        'shares similar values and appreciates sincerity over appearances.',
    imageUrl: 'assets/tulips.jpg',
    contact: '+92-300-0123457',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  // ── Faisalabad ──────────────────────────────────────────────────────────────

  Profile(
    id: 'f10',
    name: 'Asma Tariq',
    age: 20,
    city: 'Faisalabad',
    hobbies: [Hobby.cooking, Hobby.gardening, Hobby.reading],
    traits: [Trait.kind, Trait.patient, Trait.religious],
    description:
    'Assalamu Alaikum. I am a simple girl from Faisalabad who loves her family '
        'and her deen. I am currently in my second year of university. I enjoy '
        'cooking and taking care of plants. I am looking for a simple, religious '
        'and responsible man. All rishta inquiries through my father please.',
    imageUrl: 'assets/sunflowers.jpg',
    contact: '+92-341-2233445',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),
Profile(
    id: 'f32',
    name: "Ruqayya Butt",
    age: 16,
    city: "Faisalabad",
    hobbies: [Hobby.reading, Hobby.cooking, Hobby.writing],
    traits: [Trait.religious, Trait.patient, Trait.humble],
    description: "High school student excelling in Islamic studies. From a conservative family seeking early marriage proposals.",
    imageUrl: "assets/violets.jpg",
    contact: "+92-333-2345678",
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
),

Profile(
    id: 'f11',
    name: 'Urooj Bukhari',
    age: 24,
    city: 'Faisalabad',
    hobbies: [Hobby.writing, Hobby.calligraphy, Hobby.cooking],
    traits: [Trait.creative, Trait.hardworking, Trait.caring],
    description:
    'Salam! I am a teacher in Faisalabad who is passionate about education '
        'and literacy. I write poetry in Urdu as a hobby and I practice calligraphy '
        'to stay connected with our heritage. I want a husband who respects a '
        "woman's mind as much as her character. Contact my brother for proposals.",
    imageUrl: 'assets/roses.jpg',
    contact: '+92-300-5544332',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f24',
    name: 'Mariam Ahmed',
    age: 27,
    city: 'Faisalabad',
    hobbies: [Hobby.cooking, Hobby.crafts, Hobby.gardening],
    traits: [Trait.familyOriented, Trait.traditional, Trait.kind],
    description:
    'Assalamu Alaikum. I am a homemaker from Faisalabad with a love for cooking '
        'and handmade crafts. I am seeking a family-oriented partner who values '
        'a warm and well-run home.',
    imageUrl: 'assets/violets.jpg',
    contact: '+92-300-4567891',
    status: FemaleMaritalStatus.divorcee,
    hasChildren: true,
    isShortListed: false,
  ),

  // ── Multan ──────────────────────────────────────────────────────────────────

  Profile(
    id: 'f12',
    name: 'Sumayya Khan',
    age: 22,
    city: 'Multan',
    hobbies: [Hobby.cooking, Hobby.reading, Hobby.gardening],
    traits: [Trait.religious, Trait.kind, Trait.caring],
    description:
    'Assalamu Alaikum. I am from a traditional family in Multan. I take great '
        'pride in my home and family. I am a hafiza of the Quran and I hope to '
        'find a husband who values that and shares a love for the deen. '
        'My father handles all proposals.',
    imageUrl: 'assets/orchids.webp',
    contact: '+92-361-9988771',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f13',
    name: 'Mahnoor Gillani',
    age: 28,
    city: 'Multan',
    hobbies: [Hobby.fitness, Hobby.photography, Hobby.travelling],
    traits: [Trait.ambitious, Trait.extroverted, Trait.funny],
    description:
    'Hi! I am Mahnoor, a dentist from Multan. I am at a point in life where '
        'I feel ready to settle down with the right person. I am outgoing and love '
        'to explore new places. I want a partner who is confident, kind and has a '
        'sense of humor. Serious proposals via my father only.',
    imageUrl: 'assets/lillies.jpg',
    contact: '+92-300-6677553',
    status: FemaleMaritalStatus.divorcee,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f27',
    name: 'Sana Ali',
    age: 26,
    city: 'Multan',
    hobbies: [Hobby.cooking, Hobby.gardening, Hobby.crafts],
    traits: [Trait.traditional, Trait.familyOriented, Trait.honest],
    description:
    'Assalamu Alaikum. I am from a well-respected family in Multan, skilled in '
        'traditional arts and crafts. I find deep satisfaction in homemaking. '
        'Seeking a compatible and responsible partner.',
    imageUrl: 'assets/Daffodils.webp',
    contact: '+92-300-7890124',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  // ── Abbottabad ──────────────────────────────────────────────────────────────

  Profile(
    id: 'f14',
    name: 'Amna Qureshi',
    age: 23,
    city: 'Abbottabad',
    hobbies: [Hobby.photography, Hobby.travelling, Hobby.reading],
    traits: [Trait.creative, Trait.introverted, Trait.patient],
    description:
    'Salam! I am Amna from Abbottabad. Growing up surrounded by mountains has '
        'given me a deep love for nature and photography. I am a quiet person who '
        'expresses herself better through a camera lens than words. Looking for '
        'someone gentle and understanding. Contact my father for proposals.',
    imageUrl: 'assets/tulips.jpg',
    contact: '+92-992-1122334',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f15',
    name: 'Bushra Ayub',
    age: 26,
    city: 'Abbottabad',
    hobbies: [Hobby.cooking, Hobby.fitness, Hobby.writing],
    traits: [Trait.hardworking, Trait.caring, Trait.religious],
    description:
    'Assalamu Alaikum. I am a nurse from Abbottabad who has dedicated her '
        'career to helping others. I believe in putting Allah first in everything. '
        'I want a husband who is kind, family-oriented and has a stable life. '
        'I am not looking for perfection, just sincerity. Wali is my brother.',
    imageUrl: 'assets/daisies.webp',
    contact: '+92-300-8877665',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f26',
    name: 'Amina Yousuf',
    age: 20,
    city: 'Abbottabad',
    hobbies: [Hobby.painting, Hobby.reading, Hobby.travelling],
    traits: [Trait.educated, Trait.kind, Trait.humble],
    description:
    'Assalamu Alaikum. I am a medical student from Abbottabad with a passion '
        'for helping others. I am family-oriented and religiously committed. '
        'Looking for someone with similar values and a caring nature.',
    imageUrl: 'assets/roses.jpg',
    contact: '+92-333-6789013',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  // ── Hyderabad ───────────────────────────────────────────────────────────────

  Profile(
    id: 'f16',
    name: 'Nadia Memon',
    age: 25,
    city: 'Hyderabad',
    hobbies: [Hobby.cooking, Hobby.calligraphy, Hobby.gardening],
    traits: [Trait.kind, Trait.patient, Trait.religious],
    description:
    'Assalamu Alaikum. I am Nadia from Hyderabad. I am a homely person who '
        'finds joy in small things — a good meal, a tidy home and quality time '
        'with family. I am looking for a simple, honest and God-fearing man to '
        'build a life with. Proposals through my father please.',
    imageUrl: 'assets/daisies.webp',
    contact: '+92-221-3344556',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f17',
    name: 'Rabia Soomro',
    age: 21,
    city: 'Hyderabad',
    hobbies: [Hobby.reading, Hobby.writing, Hobby.painting],
    traits: [Trait.creative, Trait.introverted, Trait.ambitious],
    description:
    'Salam! I am in my final year of a literature degree in Hyderabad. '
        'I am a reader and a writer at heart. I dream of a life where I can '
        'continue learning and growing even after marriage. I want a husband '
        'who sees education in a woman as a blessing, not a threat. '
        'Contact my uncle who is my wali.',
    imageUrl: 'assets/lillies.jpg',
    contact: '+92-300-4455661',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  // ── Peshawar ────────────────────────────────────────────────────────────────

  Profile(
    id: 'f18',
    name: 'Zara Afridi',
    age: 24,
    city: 'Peshawar',
    hobbies: [Hobby.cooking, Hobby.reading, Hobby.fitness],
    traits: [Trait.hardworking, Trait.religious, Trait.caring],
    description:
    'Assalamu Alaikum. I am Zara from Peshawar. I come from a conservative '
        'family and I am proud of my values. I am a pharmacist by profession but '
        'family always comes first for me. Looking for a practicing Muslim with '
        'strong character and a kind heart. My father is my wali.',
    imageUrl: 'assets/orchids.webp',
    contact: '+92-91-5566778',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f19',
    name: 'Haleema Yusufzai',
    age: 27,
    city: 'Peshawar',
    hobbies: [Hobby.travelling, Hobby.photography, Hobby.writing],
    traits: [Trait.ambitious, Trait.extroverted, Trait.funny],
    description:
    'Salam! I am a civil servant in Peshawar with a love for my culture '
        'and heritage. I travel whenever I can and I document everything through '
        'photography. I want a partner who is secure enough to have a wife with '
        'her own ambitions. Serious families may contact my brother.',
    imageUrl: 'assets/poppies.jpg',
    contact: '+92-300-9911223',
    status: FemaleMaritalStatus.widowed,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f20',
    name: 'Sana Rehman',
    age: 18,
    city: 'Peshawar',
    hobbies: [Hobby.reading, Hobby.calligraphy, Hobby.gardening],
    traits: [Trait.religious, Trait.kind, Trait.patient],
    description:
    'Assalamu Alaikum. I just finished my FSc and my family has started '
        'looking for a suitable match for me. I am young but mature for my age. '
        'I love reading and I am learning calligraphy. I am looking for someone '
        'kind and patient who will let me continue growing. All proposals to my father.',
    imageUrl: 'assets/roses.jpg',
    contact: '+92-91-4433221',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f25',
    name: 'Khadija Raza',
    age: 23,
    city: 'Peshawar',
    hobbies: [Hobby.reading, Hobby.cooking],
    traits: [Trait.religious, Trait.honest, Trait.patient],
    description:
    'Assalamu Alaikum. I am a teacher from Peshawar, deeply committed to '
        'Islamic principles. I am looking for a practicing Muslim partner with '
        'strong character and a gentle heart.',
    imageUrl: 'assets/sunflowers.jpg',
    contact: '+92-321-5678902',
    status: FemaleMaritalStatus.virgin,
    hasChildren: false,
    isShortListed: false,
  ),

  Profile(
    id: 'f31',
    name: 'Nadia Khan',
    age: 30,
    city: 'Peshawar',
    hobbies: [Hobby.gardening, Hobby.cooking, Hobby.crafts],
    traits: [Trait.familyOriented, Trait.traditional, Trait.kind],
    description:
    'Assalamu Alaikum. I am an experienced homemaker from Peshawar seeking '
        'a mature and responsible partner. I value loyalty, patience and kindness above all else.',
    imageUrl: 'assets/tulips.jpg',
    contact: '+92-300-3456790',
    status: FemaleMaritalStatus.widowed,
    hasChildren: true,
    isShortListed: false,
  ),

];